# Generated by Django 5.1.6 on 2025-02-12 11:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kutubxonachi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ish_vaqti', models.DurationField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('jinsi', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('kitoblar_soni', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tirik', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('guruh', models.CharField(blank=True, max_length=100, null=True)),
                ('kurs', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('kitob_soni', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('janri', models.CharField(blank=True, max_length=100, null=True)),
                ('sahifa', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.muallif')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olingan_sana', models.DateTimeField(auto_now_add=True)),
                ('qaytardi', models.BooleanField(default=False)),
                ('qaytarish_sana', models.DateTimeField(blank=True, null=True)),
                ('kitob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kitob')),
                ('kutubxonachi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kutubxonachi')),
                ('talaba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.talaba')),
            ],
        ),
    ]
